### ISSUE TITLE
The release of version 44 broke 'current'

### ISSUE THREAD

**Issue by gyancarlodasilva** [google/google-visualization-issues#2185]
My google charts suddenly stopped work . until yesterday everything was great , but today ... Nothing is working.

**Comment by nbering** [comment]
Hi! I'm not part of the team, but I watch this issue repository and also provide support for my own project. I'd just like to say that your issue does not contain much for someone to go on when trying to help.
- Which components of the library are you trying to use?
- What browser are you running in?
- There are two ways to load the library... which one are you using?
- What version are you requesting from the loader? If none, try specifying one and see if it fixes your problem.
- Are you getting any errors in the JavaScript Console?
- Can you provide a live example demonstrating your issue on JSFiddle or some other similar service?

**Comment by gyancarlodasilva** [comment]
Hello,

I fix this changing the version of the google charts.

**Older**
google.charts.load("current", {packages:["corechart"]});
**New**
google.charts.load("43", {packages:["corechart"]});

**Comment by nbering** [comment]
That's great! I'm glad it's working for you now. If you would like someone to fix whatever the problem in the latest version is, it would also be helpful to report some of the other details I listed above. Otherwise, please close the issue as nothing can be done about it without further details. Thanks.

**Comment by dlaliberte** [comment]
The problem here is undoubtedly that the update I recently pushed out is causing problems, probably due to caching or propagation delays.  We're not exactly sure what the cause is, but we are changing the loader to avoid most of the possible causes.

You should be able to use '44' as well as '43'.  If not, that could be another problem, so it would be good if we could learn more details.

**Comment by jaggedsoft** [comment]
:+1: Also having the same problem with both material charts and classic charts.

> VM199:635 Uncaught TypeError: fH.pc is not a function
- It worked two days ago & works now if you use a fixed version number
- Does not work using Chrome 50.0.2645.3
- [JSFiddle not working in Chrome](https://jsfiddle.net/jaggedsoftware/tr5dsgwL/) (EDIT: Working again as of March 1st for me in Chrome)
- Works in Firefox and IE

Problem applies to both the material charts and the core charts when loading with current version like:

```
google.charts.load('current', {packages:['line']});
google.charts.load('current', {packages:['corechart']});
```

You can get it to work again by switching to a fixed version number like:

```
google.charts.load("44", {packages:["line"]});
google.charts.load("44", {packages:["corechart"]});
```

<sub>While I have your attention @dlaliberte [Request: focusTarget option on Material Charts](https://groups.google.com/forum/#!topic/google-visualization-api/Ol2yVy6mrVE) Hopefully this is an easy add thank you!</sub>

**Comment by fabregas4** [comment]
After spending a couple of hours trying to work out what had gone wrong with my charts I came across this page. Changing the version to 43 got them working again. Worst thing is that even the getting started example from the official site would not load in Chrome. Opened in IE fine. Seems a buggy version was released.

**Comment by dlaliberte** [comment]
Version 44 is fine.  The problem is probably browsers (or perhaps caching
servers) caching old redirects from 'current' to '43'.  We are not updating
anything, and yet the problem is resolving itself as people flush their
caches.  We will avoid the need for this in future releases.

On Mon, Feb 29, 2016 at 10:27 AM, fabregas4 notifications@github.com
wrote:

> After spending a couple of hours trying to work out what had gone wrong
> with my charts I came across this page. Changing the version to 43 got them
> working again. Worst thing is that even the getting started example from
> the official site would not load in Chrome. Opened in IE fine. Seems a
> buggy version was released.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/google/google-visualization-issues/issues/2185#issuecomment-190256813
> .

## 

Daniel LaLiberte https://plus.google.com/100631381223468223275?prsrc=2
dlaliberte@Google.com dlaliberte@google.com   5CC, Cambridge MA

**Comment by RoarkeRandall** [comment]
Version 44 working for me. Switching to current I get `Uncaught TypeError: Cannot read property 'aa' of undefined` when instantiating a google Table. I tried clearing my cache and it didn't help.

**Comment by fabregas4** [comment]
Yes, 44 is also fine for me.

**Comment by jaggedsoft** [comment]
Move to close, sounds like issue is resolved and current channel is working again

**Comment by nbering** [comment]
@jaggedsoft By the wide-spread nature of the issue, I'm going to bet reports will be coming in for days at least. There's been significantly increased activity on the Stack Overflow `google-visualization` tag as well. I for one would leave at least one issue open as a reference issue to direct people to until reports stop coming in.

**Comment by scytail** [comment]
The current channel is not working, as I'm working on a script and keep getting errors like "hi is not a function" even though my code worked just fine yesterday. I also get similar errors on the google charts API page itself. I agree with @nbering in that at least one issue related to this needs to stay open.

**Comment by dlaliberte** [comment]
I made a change over an hour ago that should have helped to expire the browser caches of the redirect from 'current' to older version 43 of the code, thus causing the new version 44 to be loaded.  We would be surprised to learn that doing this caused more problems, though it is conceivable.  Hopefully this should all settle down within a couple hours.

**Comment by flpms** [comment]
Hi I'm using line-chart and the not show lines. I'll send a print, I believe it's a bug, this occor when I'm draw two charts on the same page.  #2192.

![charts](https://cloud.githubusercontent.com/assets/4911643/13443460/e9e818aa-dfdf-11e5-9a9f-58b20fafae85.PNG)

**Comment by nbering** [comment]
@flpms If switching to the a specific version number as indicated above does not fix your issue, then it is unrelated to this specific issue thread.

Also, a picture tells something for diagnostics, but code and error messages are much more helpful.

**Comment by grabks** [comment]
@flpms That's really strange. I've never seen issues with drawing multiple charts with corecharts. Nor does this sound like the caching issue that @dlaliberte is talking about. Could you perhaps create a jsfiddle showing the error so that we may investigate?

**Comment by nbering** [comment]
@grabks Getting a little off-topic here, but I found @flpms had also posted this issue to stack overflow with more detail. http://stackoverflow.com/questions/35735987/google-charts-dont-display-lines-in-linechart

**Comment by grabks** [comment]
Thanks for linking me to that, @nbering. However, the jsfiddle seems fine to me, and I don't see the issue (as you said in your comment). Moreso, he's loading version `'43'` directly, so he shouldn't be experiencing the caching issues with our most recent release. My best guess is that this is occurring in some specific browser, like IE or something and @flpms simply forgot to mention that (highly important) fact.

**Comment by flpms** [comment]
Sorry I forgot to tell more information and I think its related, cause my issue was closed as duplicated. I'm run in Google Chrome browser and using with ember like I tell in Stackoverflow. If needed I delete my previous comment. Follow more informations. 

In another question PieChart doesn't work, now line chart. I changed versions `current`and version `43`, and still not working.

**Comment by grabks** [comment]
@flpms Can you create a jsfiddle that reproduces the issue? [The fiddle you posted in your StackOverflow post](https://jsfiddle.net/e4vtpjac/) works for me.

**Comment by flpms** [comment]
@grabks work for me too. I tried created another jsfidlle to reproduces using Ember both charts are broken in jsfidlle, which not is my case. I search for incompatibilities between Ember and Google Chart, and I found nothing.

Another thing to add. Google chart with material work fine.

**Comment by grabks** [comment]
@flpms Then I don't understand what issue you're experiencing. Please provide a jsfiddle that reproduces your issue.

**Comment by dlaliberte** [comment]
I made a change to the loader so that it does the redirect from 'current' to the current version (44 now) in a very different way.  It should work better for everyone now.  Thanks for your patience.

**Comment by TomasKrt** [comment]
Hi, I had the same problem with version "Calculated column must have a "type" property.×". On my page i need 2 similar column chart - i changed the code to "google.charts.load('43', {packages: ['corechart']});" One chart is ok, but the 2nd doesnt - there is empty space. containerId is differnet. Before I had these chart on the same page. When i past the code of 2nd chart on empty page, it also ok. But the problem is, that i need both on the same page. Thank you for advice.

**Comment by dlaliberte** [comment]
Tomas, the problem you are describing sounds like it is probably not related to other problems reported on this thread, which I will close now.   You should post more details to the forum for asking questions (at https://groups.google.com/forum/#!forum/google-visualization-api) unless you are fairly certain you have found a problem.  It would be best if you could point to a page that shows the problem you are experiencing so we can check it out there.

**Comment by TomasKrt** [comment]
Daniel, please, i have little problem with charts, when i first retrieves
page with chart, it show : (You called the draw ()method with the wrong
type of data rather than a DataTable or DataView), when I do refresh of
this page it show charts correctly.

Please where is the mistake, the code is
Thank you!

<script type="text/javascript"

src="https://www.gstatic.com/charts/loader.js"></script>

<script type='text/javascript'>
google.charts.load('current', {
  'packages': ['corechart']
});
google.charts.setOnLoadCallback(drawChart);

function drawChart() {
var wrapper = new google.visualization.ChartWrapper(
{"containerId":"visualizationF27B","dataTable":{"cols":[{"id":"","label":"","pattern":"","type":"string","p":{}},{"id":"","label":"vymoženo
CZK","pattern":"","type":"number","p":{}},{"id":"","label":"zbývá vymoci
CZK","pattern":"","type":"number"}],"rows":[{"c":[{"v":"červenec","f":null},{"v":15,"f":null},{"v":44,"f":null}]}],"p":null},"options":{"isStacked":true,"animation":{"duration":2500,"startup":true},"bar":{"groupWidth":
"25%"},"booleanRole":"certainty","hAxis":{"useFormatFromData":true,"viewWindow":{"max":null,"min":null},"minValue":null,"maxValue":null,"logScale":false,"gridlines":{"count":"3"}},"vAxes":[{"useFormatFromData":true,"minValue":null,"maxValue":null,"viewWindow":null,"viewWindowMode":null},{"useFormatFromData":true}],"legend":"bottom","series":{"1":{"color":"#b7b7b7"}},"title":"Celkový","fontName":"Georgia"},"state":{},"isDefaultVisualization":true,"chartType":"BarChart"}
);
wrapper.draw();
};
</script>
<div style='border: 0px darkgray solid;width:500px;'>
<div id='visualizationF27B' style='width:500px; height:200px;'></div>
</div>



2016-05-03 17:00 GMT+02:00 Daniel LaLiberte <notifications@github.com>:
